name: Bug Report
description: Report a reproducible bug in Neighbory
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting. Please provide enough details so the issue can be reproduced.
  - type: textarea
    id: description
    attributes:
      label: Problem Description
      description: What happened?
      placeholder: Describe the observed behavior and where it occurs.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction Steps
      description: How can we reproduce it?
      placeholder: |
        1. Start the application
        2. Call endpoint X
        3. Observe error Y
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: input
    id: env
    attributes:
      label: Environment
      description: OS / JDK / runtime details
      placeholder: macOS 14, OpenJDK 21.0.10
    validations:
      required: true
