name: Feature Request
description: Suggest an idea or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: 你要解决的问题
      description: 当前痛点是什么？
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: 建议方案
      description: 你期望的实现方式
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: 备选方案
      description: 是否考虑过其他实现路径？
    validations:
      required: false
