CREATE TABLE estates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(20) NOT NULL,
    name VARCHAR(100) NOT NULL,
    address VARCHAR(255),
    remark VARCHAR(255)
);
CREATE UNIQUE INDEX idx_estates_code ON estates (code);

CREATE TABLE buildings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estate_id BIGINT NOT NULL,
    code VARCHAR(20) NOT NULL,
    name VARCHAR(100) NOT NULL,
    CONSTRAINT uk_building_estate_code UNIQUE (estate_id, code),
    CONSTRAINT fk_building_estate FOREIGN KEY (estate_id) REFERENCES estates(id) ON DELETE CASCADE
);
CREATE INDEX idx_buildings_estate_id ON buildings (estate_id);

CREATE TABLE units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    building_id BIGINT NOT NULL,
    code VARCHAR(20) NOT NULL,
    name VARCHAR(100) NOT NULL,
    CONSTRAINT uk_unit_building_code UNIQUE (building_id, code),
    CONSTRAINT fk_unit_building FOREIGN KEY (building_id) REFERENCES buildings(id) ON DELETE CASCADE
);
CREATE INDEX idx_units_building_id ON units (building_id);
