CREATE TABLE billing_charges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estate_code VARCHAR(20) NOT NULL,
    unit_code VARCHAR(20) NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    due_date DATE NOT NULL,
    paid BOOLEAN NOT NULL,
    remark VARCHAR(255)
);
CREATE INDEX idx_billing_charges_estate_code ON billing_charges (estate_code);
CREATE INDEX idx_billing_charges_unit_code ON billing_charges (unit_code);

CREATE TABLE work_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    priority VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL
);
CREATE INDEX idx_work_orders_status ON work_orders (status);

CREATE TABLE parking_spaces (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(20) NOT NULL,
    occupied BOOLEAN NOT NULL,
    owner_name VARCHAR(100),
    CONSTRAINT uk_parking_spaces_code UNIQUE (code)
);
